# Generated by Django 4.0.4 on 2022-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_category_alter_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('MINI_PROJECT', 'MINI_PROJECT'), ('FINAL_PROJECT', 'FINAL_PROJECT'), ('HACKAHTON', 'HACKATHON')], max_length=20),
        ),
    ]
